[profile.default]
src = "."
out = "out"
test = "nonexistent"
script = "nonexistent"
libs = ["/home/articuno/Firewall/FirewallOnchain/lib"]
remappings = [
    "@openzeppelin/=/home/articuno/Firewall/FirewallOnchain/DeFiHackLabs/extracted_contracts/2024-02/BurnsDefi_exp/0x4fb9657ac5d311dd54b37a75cfb873b127eb21fd_Vuln_Contract/@openzeppelin/",
    "lib/=/home/articuno/Firewall/FirewallOnchain/lib/",
    "@openzeppelin/=/home/articuno/Firewall/FirewallOnchain/lib/openzeppelin-contracts/",
    "forge-std/=/home/articuno/Firewall/FirewallOnchain/lib/forge-std/src/",
    "src/=/home/articuno/Firewall/FirewallOnchain/src/"
]
via_ir = false
evm_version = "shanghai"
ignored_error_codes = [5159, 2072, 6546]
auto_detect_solc = true
